name: E2E with Cypress
on: push
jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    env:
      VITE_REACT_APP_DOMAIN: ${{ secrets.AUTH0_CLIENT_DOMAIN }}
      VITE_REACT_APP_CLIENTID: ${{ secrets.AUTH0_CLIENT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
